export const LOAD_RESTAURANT = 'LOAD_RESTAURANT';
export const REQUEST_REST_PENDING = 'REQUEST_REST_PENDING';
export const REQUEST_REST_SUCCESS = 'REQUEST_REST_SUCCESS';
export const REQUEST_REST_FAILED = 'REQUEST_REST_FAILED';